### ISSUE TITLE
Error found while deleting customer

### ISSUE THREAD

**Issue by pasyangtan** [pasyangtan/WaterBillingSystem#1]
While deleting customer, the program throws the error. Please check the reason for the error.

**Comment by Sameersth015** [comment]
![del1](https://user-images.githubusercontent.com/102210766/162781568-dd5797b4-db7a-417b-8c1d-97c91d222a4c.jpg)
![del 2](https://user-images.githubusercontent.com/102210766/162781583-5b816d09-339b-4bf5-a789-67cd08eb612c.jpg)
The issue is solved there was a minor mistake in the file del.php on line 22.  There was (name="Id") instead of (name="id"). Now you are able to delete the customers.
