### ISSUE TITLE
In the staff client page when we click on logo it must direct to staff homepage instead it is going to client homepage 

### ISSUE THREAD

**Issue by SthBishal** [pasyangtan/WaterBillingSystem#4]
![280782406_1218085232277807_3763491243352289786_n](https://user-images.githubusercontent.com/101698265/168474272-ad531d9c-7a2c-4573-9cff-81e66a297098.jpg)
@Sameersth015

**Comment by Sameersth015** [comment]
![Screenshot from 2022-05-15 19-00-25](https://user-images.githubusercontent.com/102210766/168474757-927b5b5b-4429-451a-9b36-6a34b8c25970.png)
![Screenshot from 2022-05-15 19-00-33](https://user-images.githubusercontent.com/102210766/168474759-88aa27c7-a404-41c7-ad7e-86678002815e.png)
There was a slight mistake on the line 116 of the eclients.php file where insteading of redirecting it to emp home it was taking the user(in this case staff) to the clientshome.php which is homepage of client. now the issue is solved you can have a look.

**Comment by Sameersth015** [comment]
![Screenshot from 2022-05-15 19-00-25](https://user-images.githubusercontent.com/102210766/168474757-927b5b5b-4429-451a-9b36-6a34b8c25970.png)
![Screenshot from 2022-05-15 19-00-33](https://user-images.githubusercontent.com/102210766/168474759-88aa27c7-a404-41c7-ad7e-86678002815e.png)
There was a slight mistake on the line 116 of the eclients.php file where insteading of redirecting it to emp home it was taking the user(in this case staff) to the clientshome.php which is homepage of client. now the issue is solved you can have a look.
