### ISSUE TITLE
After clicking add client on the client page the following error pops up

### ISSUE THREAD

**Issue by SthBishal** [pasyangtan/WaterBillingSystem#6]
![Screenshot (242)](https://user-images.githubusercontent.com/101698265/168475529-ac1dc48d-af00-441c-973c-a36de0aea11e.png)
@Sameersth015

**Comment by Sameersth015** [comment]
![Screenshot from 2022-05-15 19-28-19](https://user-images.githubusercontent.com/102210766/168476127-9986e5c9-0050-4a58-b30b-f9fe31506e39.png)
The issue was caused due to error in eaddclient.php and eaddclient1.php . The file wasn't updated according to the feature we added where client have there own username and password to login to the system. So, now everything is added and updated and you can add clients .
![Screenshot from 2022-05-15 19-31-49](https://user-images.githubusercontent.com/102210766/168476252-7d3dc90c-5c7f-49ee-acf8-c66733fb85db.png)
